# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: CarService API
  description: CarService API, 返回值的json格式是默认用data包起来
  version: "1.0.0"
# the domain of the service
host: 120.26.65.167:8080
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /api/v1/
produces:
  - application/json
paths:
   /store:
    get:
      summary: 门店列表
      description: 门店列表
      parameters:
        - name: course_id
          in: query
          type: integer
          format: int32
          description: 课程id
          required: true
      tags:
        - Store
      responses:
        200:
          description: 门店列表
          schema:
            $ref: '#/definitions/ShoppingList'
definitions:
  ShoppingList:
    type: object
    description: 买断商品列表
    properties:
      question_count:
        type: integer
        format: int32
        description: 提问次数
      price:
        type: integer
        format: int32
        description: 现价
