# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: CarService API
  description: CarService API, 返回值的json格式是默认用data包起来
  version: "1.0.0"
# the domain of the service
host: 120.26.65.167:8080
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /api/v1/
produces:
  - application/json
paths:
   /store:
    get:
      summary: 门店列表
      description: 门店列表
      parameters:
        - name: city
          in: query
          type: string
          format: string
          description: 城市名
          required: true
        - name: district
          in: query
          type: string
          description: 区名
          required: false
        - name: tags
          in: query
          type: string
          description: 标签列表,用英文逗号隔开
          required: false
        - name: limit
          in: query
          type: string
          format: int32
          description: 返回的数量,默认5
        - name: offset
          in: query
          type: string
          format: int32
          description: 偏移量,默认0
      tags:
        - Store
      responses:
        200:
          description: 门店列表
          schema:
            $ref: '#/definitions/StoreList'
definitions:
  StoreSimple:
    type: object
    description: 门店简介
    properties:
      id:
        type: integer
      name:
        type: string
        description: 名称
      address:
        type: string
        description: 完整地址
      latitude:
        type: number
        format: double
        description: 纬度
      longitude:
        type: number
        format: double
        description: 经度
      tags:
        type: array
        description: 标签列表
        items:
          $ref: '#/definitions/Tag'
  Tag:
    type: object
    description: 标签
    properties:
      id: 
        type: integer
      name:
        type: string        
  StoreList:
    type: object
    description: 门店列表
    properties:
      offset:
        type: integer
        format: int32
        description: 提问次数
      limit:
        type: integer
        format: int32
        description: 现价
      count:
        type: integer
        format: int32
        description: 总数量
      list:
        type: array
        items: 
          $ref: '#/definitions/StoreSimple'
